#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-ojalgo
Version  : 43
Release  : 2
URL      : https://github.com/optimatika/ojAlgo/archive/v43.tar.gz
Source0  : https://github.com/optimatika/ojAlgo/archive/v43.tar.gz
Source1  : https://repo1.maven.org/maven2/org/ojalgo/ojalgo/43.0/ojalgo-43.0.jar
Source2  : https://repo1.maven.org/maven2/org/ojalgo/ojalgo/43.0/ojalgo-43.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-ojalgo-data = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-mvn

%description
# oj! Algorithms
oj! Algorithms - ojAlgo - is Open Source Java code that has to do with mathematics, linear algebra and optimisation.

%package data
Summary: data components for the mvn-ojalgo package.
Group: Data

%description data
data components for the mvn-ojalgo package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ojalgo/ojalgo/43.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/ojalgo/ojalgo/43.0/ojalgo-43.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ojalgo/ojalgo/43.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/ojalgo/ojalgo/43.0/ojalgo-43.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/ojalgo/ojalgo/43.0/ojalgo-43.0.jar
/usr/share/java/.m2/repository/org/ojalgo/ojalgo/43.0/ojalgo-43.0.pom
